apiVersion: v1
appVersion: "4.2.0"
description: A Helm chart for the Aqua Console Components
engine: gotpl
home: https://www.aquasec.com/
icon: https://www.aquasec.com/wp-content/uploads/2016/05/aqua_logo_fullcolor.png
sources:
- https://github.com/aquasecurity/aqua-helm
name: aqua-app-server
version: [[ .Version ]]
